# netlify.toml

# Build settings
[build]
  # Directory to change to before starting build.
  base = "wheres-waldo-frontend"

  # Build command.
  command = "npm run build"

  # Directory to publish (relative to root of your repository).
  publish = "dist"

